### ISSUE TITLE
mediasoup-sys 0.1.0 failed to build

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/docs.rs#1338]
**Crate name:** mediasoup-sys
**Build failure link:** https://docs.rs/crate/mediasoup-sys/0.1.0

**Additional details:**
I suspect the error is caused by read-only filesystem, but at the same time I can't use `OUT_DIR` because it created so long of a path prefix that openssl build (that is a part of the crate build process) would fail due to exceeding length limit for CLI arguments somewhere deep within its build system (and I'm not feeling like messing with openssl build system).

Not sure what to do here except trying to hack around build.rs in such a way that would skip building some of the libraries and linking them (which should be fine as long as the code isn't running), but I'd ideally need to have a few attempts to verify that approach actually works. Is there a Docker command I can use to mimic docs.rs build system behavior precisely?

**Comment by nazar-pc** [comment]
Yes, exiting from `build.rs` right away if `DOCS_RS` is defined helped.

**Comment by jyn514** [comment]
> Is there a Docker command I can use to mimic docs.rs build system behavior precisely?

Yes: https://forge.rust-lang.org/docs-rs/add-dependencies.html#testing-the-image

> I suspect the error is caused by read-only filesystem, but at the same time I can't use OUT_DIR because it created so long of a path prefix that openssl build (that is a part of the crate build process) would fail due to exceeding length limit for CLI arguments

Would it help if we made a symlink to OUT_DIR as the top-level directory and passed that instead? That should make the path shorter I think. But also no one else has had trouble with this, so maybe you could shrink the command-line another way?

**Comment by jyn514** [comment]
> Yes, exiting from `build.rs` right away if `DOCS_RS` is defined helped.

Oh, that works too :laughing:

**Comment by nazar-pc** [comment]
Can someone trigger rebuild of https://docs.rs/crate/mediasoup/0.7.0?
It depended on mediasoup-sys 0.1.0 and I just pushed mentioned fix in 0.1.1 so it should be buildable now as well.

**Comment by jyn514** [comment]
> Can someone trigger rebuild of https://docs.rs/crate/mediasoup/0.7.0?

Sure, done. It still failed though because you have a lockfile that pins it to 0.7.0.

**Comment by nazar-pc** [comment]
Hm... I didn't expect lock file in the library, I guess it is because of workspace usage :thinking:
I'll fix it myself then, thanks!

> Would it help if we made a symlink to OUT_DIR as the top-level directory and passed that instead? That should make the path shorter I think.

It would, but since I'm the only one, probably not worth it. Also skipping compilation of a bunch of unnecessary C++ is easier on docs.rs infra, so I think it is fine as is.

> But also no one else has had trouble with this, so maybe you could shrink the command-line another way?

I was quite surprised as well that this could happen, but I don't think I can really want to change Gyp build config without necessarily knowing what I'm doing :slightly_smiling_face: 

Thanks for very quick response :heart:
