### ISSUE TITLE
noscript fallback?

### ISSUE THREAD

**Issue by rw** [rust-lang/docs.rs#419]
Thanks for your hard work on docs.rs!

I really liked how the previous version(s) of docs.rs didn't need javascript to render essential content.

Is there an option to make the new docs.rs not require javascript to render (what seems to be 100%) static content?

**Comment by GuillaumeGomez** [comment]
What isn't working with the noscript?

**Comment by rw** [comment]
@GuillaumeGomez The following doesn't show the "Methods"/"Implementations" sections with Javascript disabled in my Chrome browser:

https://docs.rs/slab/0.4.2/slab/struct.Slab.html

I see an error in the console that the following file was not found, maybe that's the problem?

https://docs.rs/noscript-20190110-1.33.0-nightly-c2d381d39.css

**Comment by GuillaumeGomez** [comment]
Oh I see. Opening an issue on rustdoc about it.

**Comment by jyn514** [comment]
This is fixed in latest docs.rs, see e.g. https://docs.rs/odrive-rs/0.1.0/odrive_rs/ascii/struct.ODrive.html. Fixing slab/0.4.2 would require #464 which is separate from the problem itself.

**Comment by rw** [comment]
@GuillaumeGomez @jyn514 Unfortunately this appears to still occur, at least in the ODrive example you provide.

The following sections still have "display: none" set:

+ Trait Implementations
+ Auto Trait Implementations
+ Blanket Implementations

**Comment by GuillaumeGomez** [comment]
With the last version of ODrive?

**Comment by rw** [comment]
@GuillaumeGomez Thanks for the quick response. I think it's an issue with how Chrome and uBlock Origin interact. I don't know the root cause.

If I disable Javascript in the Chrome tab, and disable Javascript in uBlock Origin, the page does not render fully.

Any other combination of enable/disable causes the page to render fully.

I suspect that a lot of Rust users use ad blockers, so it might be worth keeping an eye on this. However, I don't know the root cause.
