### ISSUE TITLE
Broken link to external crate source file

### ISSUE THREAD

**Issue by pickfire** [rust-lang/docs.rs#420]
In https://docs.rs/tokio/0.2.0-alpha.6/tokio/attr.main.html, `[src]` redirected to https://docs.rs/tokio-macros/0.2.0-alpha.6/src/tokio_macros/lib.rs.html#48-120 which gives 404.

Probably related to https://github.com/rust-lang/docs.rs/blob/32074e792046a7c41c716f592c692383528515b5/src/web/mod.rs#L182-L190

**Comment by Nemo157** [comment]
This could be related to https://github.com/rust-lang/docs.rs/issues/298

**Comment by jyn514** [comment]
This may have been fixed in https://github.com/rust-lang/docs.rs/pull/487 ... If not the fix would be very similar

**Comment by pickfire** [comment]
I think that probably have not fixed it (not tested) since https://docs.rs/tokio-macros/0.2.0-alpha.6/src/tokio_macros/lib.rs.html#48-120 will be https://docs.rs/crate/tokio-macros/0.2.0/source/src/lib.rs, not sure why backward-compatibility for docs.rs is broken, IIRC source was not there.

**Comment by jyn514** [comment]
Actually looking at the crate it's because `tokio-macros` [doesn't have documentation](https://docs.rs/crate/tokio-macros/0.2.0) (#422, should be fixed by #491). Do you have any other examples of broken links? If not I think this should be closed.

**Comment by pickfire** [comment]
It does not have documentation but I mean the source link is broken, not the documentation link. See https://docs.rs/tokio/0.2.0-alpha.6/tokio/attr.main.html

**Comment by jyn514** [comment]
I'm not quite sure what you're saying. That page links to https://docs.rs/tokio-macros/0.2.0-alpha.6/src/tokio_macros/lib.rs.html#48-120 which seems reasonable. What do you think it should link to?

**Comment by pickfire** [comment]
Yes, exactly. https://docs.rs/tokio-macros/0.2.0-alpha.6/src/tokio_macros/lib.rs.html#48-120 shows **the resource does not exist**.

**Comment by jyn514** [comment]
We're going in circles here.

>  it's because tokio-macros doesn't have documentation (#422, should be fixed by #491).

If you go to [0.2.0](https://docs.rs/tokio-macros/0.2.0/src/tokio_macros/lib.rs.html#48-120) it works fine, pietro queued a rebuild and it's live.
